import { View, Text, StyleSheet } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import type { TransactionReceiptData } from '../../lib/transaction-receipt';
import type { ReceiptTheme } from '../../lib/receipt-html';
import { POWERED_BY_LABEL } from '../../constants/brand';
import { AppLogo } from '../ui/AppLogo';
import {Radius , Palette, FormColors, BRAND, Overlays, useThemedStyles } from '../../theme';
import { gradientStops } from '../../theme/gradient-utils';

type Props = {
  data: TransactionReceiptData;
  theme: ReceiptTheme;
  compact?: boolean;
};

function statusColors(tone: TransactionReceiptData['statusTone'], theme: ReceiptTheme) {
  switch (tone) {
    case 'successful':
      return { dot: theme.success };
    case 'failed':
      return { dot: theme.error };
    case 'processing':
      return { dot: Palette.pendingDot };
    default:
      return { dot: theme.warning };
  }
}

export function TransactionReceiptCard({ data, theme, compact = false }: Props) {
  const styles = useStyles();

  const status = statusColors(data.statusTone, theme);

  return (
    <View style={[styles.shell, compact && styles.shellCompact]}>
      <LinearGradient
        colors={gradientStops(theme.cardGradient)}
        start={{ x: 0, y: 0 }}
        end={{ x: 1, y: 1 }}
        style={[styles.hero, compact && styles.heroCompact]}
      >
        <View style={styles.heroBlob1} />
        <View style={styles.heroBlob2} />

        <View style={styles.brandRow}>
          <AppLogo size={compact ? 28 : 34} variant="onDark" />
          <Text style={styles.brandText}>{data.appName}</Text>
        </View>

        <Text style={[styles.amount, compact && styles.amountCompact]}>{data.amount}</Text>
        <Text style={styles.title} numberOfLines={2}>{data.title}</Text>
        <Text style={styles.when}>{data.dateTime} · {data.paymentMethod}</Text>

        <View style={styles.statusPill}>
          <View style={[styles.statusDot, { backgroundColor: status.dot }]} />
          <Text style={styles.statusText}>{data.statusLabel}</Text>
        </View>
      </LinearGradient>

      <View style={[styles.body, compact && styles.bodyCompact]}>
        <View style={styles.divider} />

        {data.rows.map((row) => (
          <View key={row.label} style={styles.row}>
            <Text style={styles.rowLabel}>{row.label}</Text>
            <Text
              style={[
                styles.rowValue,
                row.highlight && { color: theme.primaryDark, fontWeight: '800' },
              ]}
              numberOfLines={3}
            >
              {row.value}
            </Text>
          </View>
        ))}

        <View style={[styles.referenceBox, { backgroundColor: theme.surface }]}>
          <Text style={[styles.referenceLabel, { color: theme.muted }]}>Transaction reference</Text>
          <Text style={[styles.referenceValue, { color: theme.primaryDeep }]} selectable>
            {data.reference}
          </Text>
        </View>
      </View>

      <View style={[styles.footer, { backgroundColor: theme.surface }]}>
        <View style={styles.footerIconWrap}>
          <Ionicons name="shield-checkmark" size={14} color={theme.primary} />
        </View>
        <Text style={[styles.footerTitle, { color: theme.primaryDark }]}>Official transaction receipt</Text>
        <Text style={[styles.footerSub, { color: theme.muted }]}>
          Generated by {data.appName} · {data.supportEmail}
          {'\n'}
          {POWERED_BY_LABEL}
        </Text>
      </View>
    </View>
  );
}

const createStyles = (colors: import('../../theme/types').ThemeColors) => StyleSheet.create({
  shell: {
    width: 360,
    borderRadius: Radius.xl,
    overflow: 'hidden',
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
    shadowColor: BRAND.primaryDeep,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.14,
    shadowRadius: 24,
    elevation: 8,
  },
  shellCompact: {
    width: '100%',
    maxWidth: 360,
    alignSelf: 'center',
  },
  hero: {
    paddingHorizontal: 22,
    paddingTop: 22,
    paddingBottom: 20,
    alignItems: 'center',
    overflow: 'hidden',
  },
  heroCompact: {
    paddingTop: 18,
    paddingBottom: 16,
  },
  heroBlob1: {
    position: 'absolute',
    top: -24,
    right: -16,
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: Overlays.white08,
  },
  heroBlob2: {
    position: 'absolute',
    bottom: -12,
    left: -10,
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: Overlays.rgba255_255_255_005,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  brandText: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: Overlays.white82,
  },
  amount: {
    fontSize: 34,
    fontWeight: '800',
    color: colors.card,
    letterSpacing: -0.8,
    marginBottom: 4,
  },
  amountCompact: {
    fontSize: 30,
  },
  title: {
    fontSize: 15,
    fontWeight: '700',
    color: Overlays.white95,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 4,
    paddingHorizontal: 8,
  },
  when: {
    fontSize: 12,
    color: Overlays.white72,
    textAlign: 'center',
    marginBottom: 12,
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: Radius.full,
    backgroundColor: Overlays.white16,
    borderWidth: 1,
    borderColor: Overlays.rgba255_255_255_022,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.card,
    letterSpacing: 0.2,
  },
  body: {
    paddingHorizontal: 22,
    paddingTop: 4,
    paddingBottom: 16,
  },
  bodyCompact: {
    paddingHorizontal: 18,
  },
  divider: {
    height: 1,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: Overlays.rgba15_23_42_01,
    marginBottom: 4,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 16,
    paddingVertical: 11,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.glassBorder,
  },
  rowLabel: {
    flex: 0.9,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    color: colors.surface0,
  },
  rowValue: {
    flex: 1.2,
    fontSize: 14,
    fontWeight: '600',
    color: colors.dark,
    textAlign: 'right',
    lineHeight: 19,
  },
  referenceBox: {
    marginTop: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: Radius.lg,
    alignItems: 'center',
  },
  referenceLabel: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  referenceValue: {
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: 18,
  },
  footer: {
    paddingHorizontal: 22,
    paddingVertical: 16,
    alignItems: 'center',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.glassBorder,
    gap: 4,
  },
  footerIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: Overlays.violet10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  footerTitle: {
    fontSize: 12,
    fontWeight: '700',
  },
  footerSub: {
    fontSize: 11,
    textAlign: 'center',
    lineHeight: 16,
  },
});

function useStyles() {
  return useThemedStyles(createStyles);
}
